# Generated by Django 4.0.3 on 2022-04-21 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllMatches',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=50)),
                ('score', models.CharField(max_length=10)),
                ('ht_score', models.CharField(blank=True, max_length=10)),
                ('ft_score', models.CharField(max_length=10)),
                ('et_score', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_country', models.BooleanField(blank=True, null=True)),
                ('all_leagues_link', models.CharField(blank=True, max_length=255, null=True)),
                ('all_scores_link', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Federation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LeagueStandingsJson',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('season_id', models.CharField(max_length=10)),
                ('league_name', models.CharField(max_length=100)),
                ('league_table', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NationalTeam',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('stadium', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('stadium', models.CharField(blank=True, max_length=100, null=True)),
                ('country_is_real', models.CharField(blank=True, max_length=5, null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='footy_api.country')),
                ('federation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='footy_api.federation')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerEvent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(null=True)),
                ('player', models.CharField(max_length=100)),
                ('event', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=5)),
                ('home_away', models.CharField(max_length=5)),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='footy_api.allmatches')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='footy_api.team')),
            ],
        ),
        migrations.CreateModel(
            name='LeagueStandings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('league_id', models.CharField(max_length=10)),
                ('season_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('rank', models.CharField(max_length=10)),
                ('points', models.CharField(max_length=10)),
                ('matches', models.CharField(max_length=10)),
                ('goal_diff', models.CharField(max_length=10)),
                ('goals_scored', models.CharField(max_length=10)),
                ('goals_conceded', models.CharField(max_length=10)),
                ('lost', models.CharField(max_length=10)),
                ('drawn', models.CharField(max_length=10)),
                ('won', models.CharField(max_length=10)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='footy_api.competition')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='footy_api.team')),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='federation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='footy_api.federation'),
        ),
        migrations.AddField(
            model_name='country',
            name='national_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='footy_api.nationalteam'),
        ),
        migrations.AddField(
            model_name='competition',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='footy_api.country'),
        ),
        migrations.AddField(
            model_name='competition',
            name='federation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='footy_api.federation'),
        ),
        migrations.AddField(
            model_name='allmatches',
            name='away_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='footy_api.team'),
        ),
        migrations.AddField(
            model_name='allmatches',
            name='competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='footy_api.competition'),
        ),
        migrations.AddField(
            model_name='allmatches',
            name='home_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='footy_api.team'),
        ),
    ]
