# Generated by Django 4.0.3 on 2022-04-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footy_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allmatches',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
