# Generated by Django 4.0.7 on 2022-09-01 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('footy_api', '0002_alter_allmatches_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='all_leagues_link',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='all_scores_link',
            new_name='flag',
        ),
        migrations.RemoveField(
            model_name='country',
            name='federation',
        ),
        migrations.RemoveField(
            model_name='country',
            name='is_country',
        ),
        migrations.RemoveField(
            model_name='country',
            name='national_team',
        ),
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='LSCountry',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_country', models.BooleanField(blank=True, null=True)),
                ('all_leagues_link', models.CharField(blank=True, max_length=255, null=True)),
                ('all_scores_link', models.CharField(blank=True, max_length=255, null=True)),
                ('federation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='footy_api.federation')),
                ('national_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='footy_api.nationalteam')),
            ],
        ),
    ]
