apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: footy
  name: footy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: footy
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: footy
    spec:
      containers:
        - image: footy
          imagePullPolicy: Never
          name: footy
          ports:
            - containerPort: 8000
          command: []
          resources: {}
      restartPolicy: Always
status: {}
